resolver: lts-12.13

packages:
- .
- ../glpk-hs

# use local copy from github repository instead than the older hackage packages


extra-deps: 
- gasp-1.1.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

